// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UdemyIdentityServer.AuthServer.Models;

namespace UdemyIdentityServer.AuthServer.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20201212203323_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UdemyIdentityServer.AuthServer.Models.CustomUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Emai")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("customUsers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            City = "İstanbul",
                            Emai = "halil@gmail.com",
                            Password = "password",
                            UserName = "halilKaya"
                        },
                        new
                        {
                            id = 2,
                            City = "Ankara",
                            Emai = "ahmet@gmail.com",
                            Password = "password",
                            UserName = "ahmetKaya"
                        },
                        new
                        {
                            id = 3,
                            City = "Mardin",
                            Emai = "mehmet@gmail.com",
                            Password = "password",
                            UserName = "mehmetKaya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
